version: '3'
services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_DEPENDENCIES: vim curl
    container_name: search-music
    environment:
      - PORT=3001
    volumes:
      - ./project/SearchMusic/:/SearchMusic
      - ./start_catalyst/:/start_catalyst
    command: /start_catalyst/cmd.sh /SearchMusic/script/server.pl
    network_mode: 'host'
